# Test multiple headers on multiple lines
GET "https://httpbin.org/headers"
    header "Authorization" "Bearer token123"
    header "X-Custom-1" "value1"
    header "X-Custom-2" "value2"
    header "Accept" "application/json"

print "Headers test completed\!"
