// Command dslgen generates Go source code from a declarative DSL grammar
// (YAML or JSON). The generated file contains a constructor that rebuilds
// the DSL programmatically, plus a stub list of the actions you still need
// to register — turning a prototyped grammar into checked-in, reviewable
// Go code with zero runtime file loading.
//
// Usage:
//
//	dslgen -dsl grammar.yaml -package mydsl -func NewMyDSL -o mydsl_gen.go
//
// The generated code only depends on github.com/arturoeanton/go-dsl.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"github.com/arturoeanton/go-dsl/pkg/dslbuilder"
	"gopkg.in/yaml.v3"
)

func main() {
	var (
		dslFile  string
		pkgName  string
		funcName string
		outFile  string
	)
	flag.StringVar(&dslFile, "dsl", "", "DSL configuration file (YAML or JSON)")
	flag.StringVar(&pkgName, "package", "main", "package name for the generated file")
	flag.StringVar(&funcName, "func", "NewGeneratedDSL", "name of the generated constructor function")
	flag.StringVar(&outFile, "o", "", "output file (default: stdout)")

	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "dslgen - Generate Go code from a declarative DSL grammar\n\n")
		fmt.Fprintf(os.Stderr, "Usage: %s -dsl grammar.yaml [-package name] [-func Name] [-o out.go]\n\n", os.Args[0])
		flag.PrintDefaults()
	}
	flag.Parse()

	if dslFile == "" {
		flag.Usage()
		os.Exit(1)
	}

	config, err := loadConfig(dslFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	source, err := Generate(config, pkgName, funcName)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	if outFile == "" {
		fmt.Print(string(source))
		return
	}
	if err := os.WriteFile(outFile, source, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "generated %s\n", outFile)
}

func loadConfig(filename string) (*dslbuilder.DSLConfig, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		return nil, err
	}

	var config dslbuilder.DSLConfig
	ext := strings.ToLower(filename[strings.LastIndex(filename, ".")+1:])
	switch ext {
	case "yaml", "yml":
		err = yaml.Unmarshal(data, &config)
	case "json":
		err = json.Unmarshal(data, &config)
	default:
		return nil, fmt.Errorf("unsupported file format: %s", ext)
	}
	if err != nil {
		return nil, err
	}
	return &config, nil
}

// Generate produces gofmt-formatted Go source that reconstructs the DSL
// described by config.
func Generate(config *dslbuilder.DSLConfig, pkgName, funcName string) ([]byte, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by dslgen from %q grammar. DO NOT EDIT.\n\n", config.Name)
	fmt.Fprintf(&b, "package %s\n\n", pkgName)
	b.WriteString("import (\n\t\"github.com/arturoeanton/go-dsl/pkg/dslbuilder\"\n)\n\n")

	// Collect referenced actions for the stub comment.
	actionSet := map[string]bool{}
	for _, rule := range config.Rules {
		if rule.Action != "" {
			actionSet[rule.Action] = true
		}
	}
	actions := make([]string, 0, len(actionSet))
	for a := range actionSet {
		actions = append(actions, a)
	}
	sort.Strings(actions)

	fmt.Fprintf(&b, "// %s builds the %q DSL.\n", funcName, config.Name)
	if len(actions) > 0 {
		b.WriteString("//\n// Register these actions before parsing:\n")
		for _, a := range actions {
			fmt.Fprintf(&b, "//\n//\tdsl.Action(%q, func(args []interface{}) (interface{}, error) { ... })\n", a)
		}
	}
	fmt.Fprintf(&b, "func %s() (*dslbuilder.DSL, error) {\n", funcName)
	fmt.Fprintf(&b, "\tdsl := dslbuilder.New(%q)\n\n", config.Name)

	// Tokens in deterministic order. Keyword-style patterns saved by
	// SaveToYAML round-trip back to KeywordToken.
	tokenNames := make([]string, 0, len(config.Tokens))
	for name := range config.Tokens {
		tokenNames = append(tokenNames, name)
	}
	sort.Strings(tokenNames)
	for _, name := range tokenNames {
		pattern := config.Tokens[name]
		if kw, ok := keywordFromPattern(pattern); ok {
			fmt.Fprintf(&b, "\tif err := dsl.KeywordToken(%q, %q); err != nil {\n\t\treturn nil, err\n\t}\n", name, kw)
		} else {
			fmt.Fprintf(&b, "\tif err := dsl.Token(%q, %q); err != nil {\n\t\treturn nil, err\n\t}\n", name, pattern)
		}
	}
	b.WriteString("\n")

	// Rules in declaration order.
	for _, rule := range config.Rules {
		fmt.Fprintf(&b, "\tdsl.Rule(%q, %#v, %q)\n", rule.Name, rule.Pattern, rule.Action)
	}

	b.WriteString("\n\treturn dsl, nil\n}\n")

	return format.Source([]byte(b.String()))
}

// keywordFromPattern recognizes patterns produced by KeywordToken
// ((?i)\bword\b) and plain bare words, returning the keyword text.
func keywordFromPattern(pattern string) (string, bool) {
	if strings.HasPrefix(pattern, `(?i)\b`) && strings.HasSuffix(pattern, `\b`) {
		return strings.TrimSuffix(strings.TrimPrefix(pattern, `(?i)\b`), `\b`), true
	}
	for _, r := range pattern {
		isWord := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') ||
			(r >= '0' && r <= '9') || r == '_' || r == '-'
		if !isWord {
			return "", false
		}
	}
	hasLetter := strings.IndexFunc(pattern, func(r rune) bool {
		return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')
	}) >= 0
	if hasLetter && len(pattern) > 0 {
		return pattern, true
	}
	return "", false
}
